### ISSUE TITLE
Invalid HTML - image width

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#21]
I rendered an image using `\includegraphics[width=\textwidth]{image.jpg}` and it created a HTML `img` tag with `style="width:"`, which is not valid. I guess `style="width:100%;"` would be appropriate here, though I imagine also using e.g. `width=0.8\textwidth` which would be most appropriately translated to `style="width:80%;"`, etc.

**Comment by christianp** [comment]
I've submitted a pull request to plasTeX at plastex/plastex#224 to fix the empty width property. I'm not sure how to fix the multiplication, and I have no idea how TeX does the calculation.

**Comment by extigy** [comment]
`\includegraphics` arguments of the form `width=0.8\textwidth` should now work better with commit 6d26087f30311c48bb52c57e75e6481d81aa7563.

PlasTeX makes things difficult here because the argument type "dict" (which is used for arguments of the form `key1=value1,key2=value2`) supports casting the argument values to subtypes, but only one subtype can be stated that all values are cast to. With `\includegraphics` there are several possible arguments of differing types: numbers (scale), dimensions (width/height) and booleans (keepaspectratio). Setting the subtype to "dimension" fixes width/height calculations but breaks something like `scale=0.5`.

So, the commit above adds a new argument type when loading the graphicx package that is essentially a standard plasTeX dict argument type but explicitly looks for the "width" and "height" keys. If it sees them, it parses the corresponding argument value as a dimension. Other keys are parsed in the normal way. This should fix the calculation of image width and height when they are in terms of dimension macros, such as `\textwidth`.

Note that plasTeX defines `\textwidth` as exactly 6.5in, and when the resulting calculation is written to the HTML output it is written in units of pt.
