### ISSUE TITLE
Installation error - macOS

### ISSUE THREAD

**Issue by davidoslive** [coursebuilder-ncl/makecourse#38]
Following the instructions in the readme, I get as far as using the make local command but encounter the following error:

![Screenshot 2020-09-08 at 21 30 55](https://user-images.githubusercontent.com/70979443/92525150-3bd3da80-f21b-11ea-9951-e499b7b6eb0b.png)
 
ImportError: cannot import name 'config' from 'plasTex.Config'

**Comment by georgestagg** [comment]
This looks like an error that occurs when plasTeX is installed from the master git branch rather than version 2.1 (as is currently required by makecourse). The install instructions might be out of date somewhere.

Could you run the following command with the virtualenv active and then try again?

`pip install --force-reinstall --no-cache-dir plasTeX==2.1`

**Comment by davidoslive** [comment]
> This looks like an error that occurs when plasTeX is installed from the master git branch rather than version 2.1 (as is currently required by makecourse). The install instructions might be out of date somewhere.
> 
> Could you run the following command with the virtualenv active and then try again?
> 
> `pip install --force-reinstall --no-cache-dir plasTeX==2.1`

Excellent - this worked, not only for me, but also for a colleague who is also a Mac user. Thanks.
