### ISSUE TITLE
Check for and handle temporary filename collisions in the pdf2svg Imager.

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#41]
I had a really weird error where running `makecourse` gave the message `Page does not exist` but concluded with `All done!` etc. as usual, but then tikz images on the HTML versions of chapters other than the one I just added were not the images from that page, they were SVG image versions of pages from the PDF of the new chapter, which seemed extremely weird. 

Anyway, I managed to work out what the problem was - I think it was because I called the new file `images.tex`, because when I renamed this something else the problem went away. So maybe check whether there's a file called `images.tex` in `config.yml` and give an appropriate error message?

**Comment by prowlett** [comment]
Or presumably `images.md`, though I just thought of this and haven't tested it.

**Comment by georgestagg** [comment]
This most likely happened because the `pdf2svg` imager was setup to create a temporary file named `images.pdf`, colliding with the filename of the output from `pdflatex images.tex`.

I've changed the temporary filename used by the imager to something less likely to collide and added a check to see if a file with that name already exists in a483a075b9ce2cc4ab1102f9f7d00b86403035cd.

**Comment by christianp** [comment]
Rather than a different name, a different directory would guarantee that there's no collision. At the very least, add a suffix to the temporary file's name until there's no collision.

**Comment by georgestagg** [comment]
Filename collisions were handled in the pdf2svg imager better since da3b811bcc0c60dbd604506145001e3357739e7a.
