### ISSUE TITLE
Update modified pages, rather than regenerate whole site?

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#55]
Would it be worth having `makecourse` just update pages that have changed? My reasoning is that as I am adding material to my course, it is taking longer and longer to build. Usually, I have just added a new file and everything else is the same. 

Apart from build time, there are a couple of niggles that have set my thinking in this direction:

- if I re-run `makecourse` on a different day, it makes a lot of changes to files in my git repository, but most of these are just updating the "Site last generated:" date at the bottom of each page. I could imagine a version where only the updated files are built, and the wording at the bottom of the page is more like "This page last updated:". 
- if a student goes to a page of notes and sees the date at the bottom is more recent than when they last read that page, they might look for a change that isn't there.
- a new version of `makecourse` might break something on a page I wrote weeks ago (e.g. display weird, rather than crash), but I'm not checking all previous pages each time I re-run `makecourse`, I'm just checking the one I just added to make sure it looks okay.

I don't know how hard this would be to do, technically, so please forgive me if I am talking nonsense. I guess it would need to know when it last ran (perhaps it could store this in `MANIFEST.yml`) and then compare file modified dates to that date? Though it seems there may be complications wrt tracking which menu pages need to change.

**Comment by christianp** [comment]
This is typically achieved by looking at the last-modified times of the output file and the input files, and only running if the input is newer. You're right that there are a few inputs that need to be taken into account, but I think sphinx gets around this by just requiring a clean build for certain things.

**Comment by georgestagg** [comment]
The machinery for this to work is mostly already there from work Christian did a while back for markdown source. I've started extending it in 83c8564b25b6020b78df42e7daa42a1038650726 to work with tex files too.

The new "recently built" check for tex files works from a  list of input files in an auxiliary `.fls` file that `pdflatex` can be told to produce. If a `.fls` file exists, `makecourse` will read it and check the modified time on all the input files to see if it can skip rebuilding the `.tex` source.

Since `makecourse` normally cleans up LaTeX auxiliary files after processing, this only works well if makecourse is run in "lazy" mode (running with the `-z` flag), so that the `.fls` file is not deleted. If you start using lazy mode to take advantage of this you might have to update your `.gitignore` to ignore more aux files that are no longer being cleaned up.

**Comment by prowlett** [comment]
This appears to be excellent. My module was building at 3.5 minutes (`time makecourse`) but `time makecourse -z` on the second run took 1.2 seconds to decide there was nothing to do. Is there a disadvantage to running this way? Or to making the default `makecourse` delete build files excluding the `.fls` and doing this each time?

**Comment by georgestagg** [comment]
I remember the idea being that I wanted `makecourse` to clean up after itself, but I guess there is a difference between the `tmp` folder created by `makecourse` and aux files created by `pdflatex`. Perhaps I should only concern myself with the former. I don't think specially excluding the `.fls` file is the right approach.

I think at some point I will simply switch things around so that the behaviour when running with `-z` is the default, and at that point close the issue.

**Comment by prowlett** [comment]
It's certainly nice of `makecourse` to clean up, so that I can easily find the editable files. But, frankly, `pdflatex` doesn't do this, so I guess people are used to this problem when using LaTeX and there's no real reason why `makecourse` should make good this issue for `pdflatex`. You move the PDF, which is the big file, so I guess there isn't an issue with duplicate files adding unnecessarily to the overall size of the files.

**Comment by christianp** [comment]
As you've seen, the reason you don't delete the auxiliary files is so you don't have to repeat work next time you rebuild. I think leaving auxiliary files should be the default behaviour.

**Comment by georgestagg** [comment]
Yes, I'm convinced. The default behaviour from 33a5a0cc13e2864e0a20f3e3173ebd43a4a3fc9d is to not delete LaTeX auxiliary files.
