### ISSUE TITLE
\alttext in beamer requires graphicx

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#62]
It seems there is something going on with `graphicx` and `\alttext`. I don't know if this is related to #44 so I'm starting a new issue rather than reopening that one.

This runs fine in `makecourse`.

```
\documentclass{beamer}
\begin{document}
\begin{frame}
    \includegraphics{chessboard.pdf}
\end{frame}
\end{document}
```

However, this doesn't - it throws `AttributeError: 'NoneType' object has no attribute 'altText'`. 

```
\documentclass{beamer}
\usepackage{makecourse}
\begin{document}
\begin{frame}
    \includegraphics{chessboard.pdf}\alttext{Chessboard}
\end{frame}
\end{document}
```

But this works. 

```
\documentclass{beamer}
\usepackage{graphicx}
\usepackage{makecourse}
\begin{document}
\begin{frame}
    \includegraphics{chessboard.pdf}\alttext{Chessboard}
\end{frame}
\end{document}
```

Since @georgestagg previously said in #44 that `\alttext` "should now always be available in plasTeX, without needing to import `graphicx`", this seems odd. 

It is not a problem to explicitly include `graphicx` as a workaround.

**Comment by georgestagg** [comment]
The `\alttext` macro is indeed available, but when `graphicx` isn't loaded the `\includegraphics` macro is not defined and so `\alttext` can't find an item to actually attach the alt text to. #44 was different because the alt text was attaching to a `tikzpicture`, so `graphicx` wasn't needed at all. I will try to improve the error message thrown here to make it a bit clearer what is going on.

In the first example, I was surprised to see it work. Presumably the `beamer` document class silently loads `graphicx` which is why this works in LaTeX. I'll tweak the plasTeX beamer implementation to do the same.

Apologies, but things are very busy here right now and it might be a while between commits -- I would suggest sticking with explicitly loading `graphicx` for now.

**Comment by prowlett** [comment]
Thanks. Yes, I was surprised the first one worked too!
