### ISSUE TITLE
Add PyPDF2 prerequisite to README.md

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#64]
Ref. 7570838 and #61.

**Comment by georgestagg** [comment]
PyPDF2 has been added to `requirements.txt` so it should automatically be installed when the instruction saying to run `pip install -r requirements.txt` is run.

**Comment by prowlett** [comment]
I was looking at the bit under 'Prerequisites', which say

> Install `pdf2svg`, `pdftoppm` and `libyaml` using your standard package manager (`apt install pdf2svg poppler-utils libyaml-dev`).

**Comment by georgestagg** [comment]
Ah yes. Those are required system packages, rather than python packages.

While a `python3-pypdf2` system package does exist in Ubuntu, adding it to the list there would be at odds with how we have handled other python packages (for example, `pyppeteer`). For those packages we avoid installing them systemwide and install them in a virtualenv with `pip` instead.
